# Generated by Django 4.0.4 on 2022-05-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_note_autors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='create_add',
            new_name='date_add',
        ),
        migrations.RemoveField(
            model_name='note',
            name='autors',
        ),
        migrations.RemoveField(
            model_name='note',
            name='update_at',
        ),
        migrations.AddField(
            model_name='note',
            name='date_up',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
        migrations.AlterField(
            model_name='note',
            name='message',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
