# Generated by Django 4.0.4 on 2022-05-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.note'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Активно'), (1, 'Отложено'), (3, 'Выполнено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
