# Generated by Django 4.0.4 on 2022-06-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_comment_comment_alter_comment_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Дело', 'verbose_name_plural': 'Список дел'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AddField(
            model_name='note',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Активно'), (1, 'Отложено'), (3, 'Выполнено')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='note',
            name='relevant',
            field=models.BooleanField(default=False, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Дела'),
        ),
    ]
